### ISSUE TITLE
email configuration for each business/company

### ISSUE THREAD

**Issue by kwiki30** [crater-invoice/crater#1076] opened 2022-10-26 13:46 UTC
**Describe the bug**
after creating a new company/business in crater, we tried setting up the mail adres for the other company. 
When one of the companies changes their email configuration this also changes for the other companies. 

Also in the test mails sent the company logo seems to be taken from the first company created.

**Expected behavior**
We would expect every company to be able to get their own email configuration so that they can use their emails and receive the messages from their clients;. With their Logo

**Screenshots**
Not applicable

**Please complete the following information:**
- Crater version: 6.0.6
- PHP version: 7.4
- Database type and version: phpMyAdmin 5.1.0

**Optional info**
- OS:  [e.g. Ubuntu]
- Browser: [e.g. chrome, safari]

**Comment by mohitpanjwani** [comment] 2022-10-26 14:25
Duplicate of https://github.com/crater-invoice/crater/issues/883

**Closed by mohitpanjwani** 2022-10-26 14:25 UTC
Labels: duplicate
