### ISSUE TITLE
Cannot use float in quantity input on v5

### ISSUE THREAD

**Issue by flayks** [crater-invoice/crater#604] opened 2021-11-30 16:47 UTC
**Describe the bug**
I just upgraded to v5 from v4.2 and I see that I cannot use float numbers in the quantity input. That is quite problematic because I charge per day and often I use half or quarter days.

**Expected behavior**
Be able to use 1.5 or 1.75 as quantity

**Please complete the following information:**
- Crater version: 5.0.0
- PHP version: 7.4 (FPM via Docker)
- Database type and version: MySQL

**Optional info**
- OS: macOS 12
- Browser: Brave

**Comment by swiffer** [comment] 2021-11-30 17:46
Ye, same here :) - it is working in the mobile app so caused by browser validation I guess.

**Comment by mohitpanjwani** [comment] 2021-11-30 17:49
Will get it fixed asap in a minor release tomorrow or day after that. 👍

**Comment by flayks** [comment] 2021-11-30 17:49
Definitely, it looks like a pattern not accepting floats. Just adding a `step="any"` should fix the issue I think!

**Comment by mohitpanjwani** [comment] 2021-12-01 12:04
Fixed in https://github.com/crater-invoice/crater/commit/0f99568eafa3927d3f049c09a2910a56e8345ba9

Will close this as soon as we release a minor update tonight.

**Closed** 2021-12-06 08:47 UTC
