### ISSUE TITLE
Customer's Primary Currency should convert to my Preferred Currency.

### ISSUE THREAD

**Issue by JadeMerle** [crater-invoice/crater#353] opened 2021-01-23 09:01 UTC
I'm a new user of Crater, having made the move from Wave Invoicing. I previously used Wave but they're limiting their services to only the US and Canada and potentially abroad businesses (like myself) in the future.

One thing that Wave Invoicing allowed me to do was invoice my customers using **their** currencies. So my American clients got their invoices in USD. My Dubai-based clients got their invoices in AED. 

I saw that Crater did this, too, hence why I made the shift, finding it the closest and aesthetically most pleasing invoicing software to Wave that I've found.

**However**
In Reports on Wave Invoicing, all invoiced currencies were converted (approximately) to my preferred currency (AED).

I noticed that after _manually_ migrating my invoices from Wave Invoicing to Crater that my USD invoices did not convert to my preferred currency (AED). For example, the a 2,500 USD invoice shows up as 2,500 AED, throwing the reports and monthly chart off.

I do not code nor know how to. I'm not sure if this is a bug or if this is a feature that needs to be worked into the platform or is this something I have to do from my side?

Any insight would be great!

**Comment by ggiak** [comment] 2021-01-23 12:10
@JadeMerle currency rates are moving rapidly.
To tackle this issue, you can create a custom field with the foreign currency you wish to display (USD) and add the value manually at the current currency rates.

**Comment by JadeMerle** [comment] 2021-01-23 12:45
> 
> 
> @JadeMerle currency rates are moving rapidly.
> To tackle this issue, you can create a custom field with the foreign currency you wish to display (USD) and add the value manually at the current currency rates.

Hi, I'm not sure I'm following. Can you explain further?

**Comment by JadeMerle** [comment] 2021-01-28 13:25
Still haven't found a resolution for this issue. Any tips are still welcome!

**Comment by mohitpanjwani** [comment] 2021-01-29 04:26
> I'm a new user of Crater, having made the move from Wave Invoicing. I previously used Wave but they're limiting their services to only the US and Canada and potentially abroad businesses (like myself) in the future.
> 
> One thing that Wave Invoicing allowed me to do was invoice my customers using **their** currencies. So my American clients got their invoices in USD. My Dubai-based clients got their invoices in AED.
> 
> I saw that Crater did this, too, hence why I made the shift, finding it the closest and aesthetically most pleasing invoicing software to Wave that I've found.
> 
> **However**
> In Reports on Wave Invoicing, all invoiced currencies were converted (approximately) to my preferred currency (AED).
> 
> I noticed that after _manually_ migrating my invoices from Wave Invoicing to Crater that my USD invoices did not convert to my preferred currency (AED). For example, the a 2,500 USD invoice shows up as 2,500 AED, throwing the reports and monthly chart off.
> 
> I do not code nor know how to. I'm not sure if this is a bug or if this is a feature that needs to be worked into the platform or is this something I have to do from my side?
> 
> Any insight would be great!

Hey 👋 

This has been a long standing issue when using multiple currencies. The problem is that in order to fix this we would need to integrate with a currency exchange API. 

I am looking for a Free API so the users do not have configure anything and it just works like its supposed to. 

But that’s not it, we also need to think about users who run Crater on private network or locally 🤔

**Comment by JadeMerle** [comment] 2021-02-22 15:41
> 
> 
> > I'm a new user of Crater, having made the move from Wave Invoicing. I previously used Wave but they're limiting their services to only the US and Canada and potentially abroad businesses (like myself) in the future.
> > One thing that Wave Invoicing allowed me to do was invoice my customers using **their** currencies. So my American clients got their invoices in USD. My Dubai-based clients got their invoices in AED.
> > I saw that Crater did this, too, hence why I made the shift, finding it the closest and aesthetically most pleasing invoicing software to Wave that I've found.
> > **However**
> > In Reports on Wave Invoicing, all invoiced currencies were converted (approximately) to my preferred currency (AED).
> > I noticed that after _manually_ migrating my invoices from Wave Invoicing to Crater that my USD invoices did not convert to my preferred currency (AED). For example, the a 2,500 USD invoice shows up as 2,500 AED, throwing the reports and monthly chart off.
> > I do not code nor know how to. I'm not sure if this is a bug or if this is a feature that needs to be worked into the platform or is this something I have to do from my side?
> > Any insight would be great!
> 
> Hey 👋
> 
> This has been a long standing issue when using multiple currencies. The problem is that in order to fix this we would need to integrate with a currency exchange API.
> 
> I am looking for a Free API so the users do not have configure anything and it just works like its supposed to.
> 
> But that’s not it, we also need to think about users who run Crater on private network or locally 🤔

Ah, I understand! Well, I guess until that happens, I'll convert them to my currency for Crater and add notes for clients to make payments in their currency. Thanks for the insight, @mohitpanjwani!

**Comment by noxtras** [comment] 2021-03-13 09:58
In regards to currency, that is easily fixed, while still allowing users to use it offline:
When you try to make an invoice to a customer in another currency than the item, you just ask the user to input the exchange rate.
It's really not OK to just make the exchange 1:1
I think this should be an easy fix. I'm not familiar with Laravel , otherwise i would push a commit myself.

**Comment by mohitpanjwani** [comment] 2021-03-19 04:55
@noxtras I absolutely agree with you and that's what we've decided to go with. 

This will be fixed in the next update. So you'll be asked to enter currency exchange rate manually if your base currency in the company is different than the currency of the Invoice. 

We're also adding the ability to choose a different currency on Invoice, Estimate & Payment specifically so you're not forced to always go with customer's selected currency.

**Comment by mohitpanjwani** [comment] 2021-03-19 04:57
In future, when we build the plugin marketplace. I think we can create different plugin drivers for specific currency exchange APIs which users can configure according to their choice. So they don't have to bother entering currency exchange rate every single time.

**Comment by abhijeetvijai** [comment] 2021-03-19 05:57
Hey, I just came through this FREE API for currency conversion, I hope it will be useful - https://www.currencyconverterapi.com/

You can give each user an option to configure their own API url which they can simply register and get by themselves. Thanks.

**Comment by mohitpanjwani** [comment] 2022-02-05 11:14
Released on V5

**Closed by mohitpanjwani** 2022-02-05 11:14 UTC
